#summit_xl:
# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

/summit_xl/gazebo_ros_control:
  pid_gains: # Required because we're controlling an effort interface
      arm_shoulder_pan_joint: {p: 4000,  d: 200, i: 1, i_clamp: 1}
      arm_shoulder_lift_joint: {p: 10000,  d: 200, i: 1, i_clamp: 1}
      arm_elbow_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
      arm_wrist_1_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
      arm_wrist_2_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
      arm_wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 

/gazebo_ros_control:
  pid_gains: # Required because we're controlling an effort interface
      shoulder_pan_joint: {p: 4000,  d: 200, i: 1, i_clamp: 1}
      shoulder_lift_joint: {p: 10000,  d: 200, i: 1, i_clamp: 1}
      elbow_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
      wrist_1_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
      wrist_2_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
      wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 