manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_joint
    - arm_wrist_1_joint
    - arm_wrist_2_joint
    - arm_wrist_3_joint
  gains:
    arm_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
mover_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_back_left_wheel
    - joint_back_right_wheel
    - joint_front_left_wheel
    - joint_front_right_wheel
  gains:
    joint_back_left_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_back_right_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_front_left_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_front_right_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1